-- Migração para o Projeto Cisterna Deivi (SEADES / AGENDHA)
CREATE TABLE IF NOT EXISTS cisterna_beneficiarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo TEXT NOT NULL,
    cpf TEXT,
    rg TEXT,
    nis TEXT,
    telefone TEXT,
    municipio TEXT DEFAULT 'GLÓRIA',
    comunidade TEXT,
    implementacao TEXT DEFAULT 'CISTERNA DE CONSUMO 16M³',
    contrato TEXT DEFAULT '040/2024 – SEADES/AGENDHA',
    status TEXT DEFAULT 'Ativo',
    observacoes TEXT,
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para busca rápida
CREATE INDEX IF NOT EXISTS idx_cisterna_beneficiarios_nome ON cisterna_beneficiarios (nome_completo);
CREATE INDEX IF NOT EXISTS idx_cisterna_beneficiarios_cpf ON cisterna_beneficiarios (cpf);
CREATE INDEX IF NOT EXISTS idx_cisterna_beneficiarios_municipio ON cisterna_beneficiarios (municipio);
